"""add audio_renditions table and waveform_key to tracks

Revision ID: 99d6d7e114e4
Revises: 489f5018efa3
Create Date: 2026-09-20 16:14:54.283557+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d6d7e114e4'
down_revision: Union[str, None] = '489f5018efa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_renditions',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('codec', sa.String(length=50), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_renditions_id'), 'audio_renditions', ['id'], unique=False)
    op.create_index(op.f('ix_audio_renditions_storage_key'), 'audio_renditions', ['storage_key'], unique=False)
    op.create_index(op.f('ix_audio_renditions_track_id'), 'audio_renditions', ['track_id'], unique=False)
    op.add_column('tracks', sa.Column('waveform_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'waveform_key')
    op.drop_index(op.f('ix_audio_renditions_track_id'), table_name='audio_renditions')
    op.drop_index(op.f('ix_audio_renditions_storage_key'), table_name='audio_renditions')
    op.drop_index(op.f('ix_audio_renditions_id'), table_name='audio_renditions')
    op.drop_table('audio_renditions')
    # ### end Alembic commands ###
